version: "3.7"

services:

  reverseproxy:
    image: nginx:test
    ports:
      - "80:80"
    restart: always

  testapi:
    depends_on:
      - reverseproxy
    image: testdotnetapp_image
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: always

  db:
    image: postgres:14.5-bullseye
    environment:
      - POSTGRESQL_USERNAME=mydb
      - POSTGRESQL_PASSWORD=mydb123
      - POSTGRESQL_DATABASE=mydb
  
    volumes:
      /app/pgdata:/var/lib/postgresql/data
    expose:
      5432
  