version: "3.7"

services:

  db:
    image: postgres:14.5-bullseye
    container_name: PGDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
    volumes:
      - /app/pgdataa:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


  reverseproxy:
    build: ./nginx/
    container_name: reverseproxy
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
      - /etc/nginx/ssl/private.key:/etc/nginx/ssl/private.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  testapi:
    depends_on:
      - db
      - reverseproxy
    container_name: frontend
    image: dotnettest
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: always


  