version: "3.7"

services:

  db:
    image: postgres:14.5-bullseye
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
    volumes:
      - /app/pgdataa:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


  reverseproxy:
    image: nginx:test
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always

  testapi:
    depends_on:
      - db
      - reverseproxy
     
    image: dotnettest
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: always


  